### ISSUE TITLE
Blender 2.8 [$430]

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#166]
This issue is used to track the progress of the Blender 2.8 port of LuxCore's Blender addon.
You can contribute to the development by [raising the bounty](https://www.bountysource.com/issues/58875521-blender-2-8?utm_campaign=plugin&utm_content=tracker%2F80143047&utm_medium=issues&utm_source=github) on this issue.

### Info about the required changes:

* [Changes Overview](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API)
* [API Docs](https://docs.blender.org/api/blender2.8/)
---
* https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/UI_API
* https://wiki.blender.org/index.php/Dev:2.8/Source/Python/UpdatingScripts
* https://github.com/nortikin/sverchok/issues/1783
* https://devtalk.blender.org/t/prepping-addons-for-2-8/265/8
* interesting stuff about the new depsgraph: https://wiki.blender.org/wiki/Source/Depsgraph
* new opengl draw api: https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Draw_API
* New callbacks: https://developer.blender.org/D3977
* new timer API: https://docs.blender.org/api/blender2.8/bpy.app.timers.html
* https://blenderartists.org/t/2-80-cheat-sheet-for-updating-add-ons/1148974
* Changes in depsgraph handling: https://developer.blender.org/rBe693918d40741b0839cea84d2e0c386cc262e0c3
* https://docs.blender.org/api/blender2.8/bpy.types.Depsgraph.html

#### Preparation (still 2.79 compatible):

* [x] Move all classes that need to be registered out of `__init__.py` files (so auto_load.py can find them)
  * [x] Base nodes
  * [x] Node trees
  * [x] Operators
* [x] Change all inheritance chains involving `bpy.types` classes into multi inheritance (e.g. if we have base class `LuxCoreNode`, then subclasses like `LuxCoreNodeMatte` should use multi inheritance: `LuxCoreNodeMatte(bpy.types.Node, LuxCoreNode)`)
  * [x] Nodes
  * [x] Node trees
  * [x] Node sockets
  * [x] Operators
  * [x] Menus
* [x] Use auto_load.py instead of `bpy.utils.register_module` (deprecated in 2.80)

#### 2.80 Port

Basics:
* [x] Register node trees
* [x] UI
  * [X] Port our custom UI panels, adapt to single-column layout
  * [x] Fix ui/texture.py, a lot has changed in the API (I think it was mostly copied from Blender code, so we can try to do that again)
  * [x] Move our custom imageviewer panels to the right side (out of the tools panel)
  * [ ] Can we impose an order on Blender panels? Currently they are sometimes mixed with ours in a non-optimal way.
  * [x] Create a unified cache panel that contains PhotonGI, DLSC and Env. Light Cache settings (the latter will be used for all environment lights, which shouldn't be a problem because usually there's only one)
  * [x] We can't use the `template_ID()` function from the Blender API for our material UI because we need not only a custom "new" operator, but also a custom "copy" operator (otherwise the node tree is not copied and two different materials share the same node tree). So we need to build our own UI that looks as close to the `template_ID()` result as possible (see the 2.79 BlendLuxCore code for an example)
* [x] Check if we should use `depsgraph.scene` or `depsgraph.scene_eval` (documentation is missing, read the Blender source code or ask in devtalk) -> Cycles uses `scene_eval`, so we should do the same
* [x] Scene export/conversion
  * [x] Port mesh export code
    * [x] port pyluxcore conversion function (C++)
    * [x] new mesh api: https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Mesh_API
  * [x] Object export (I want to rework this so it works with shared meshes and instances out of the box and reliable in viewport render)
    * [x] Instance export
    * [x] Transformation update in viewport
    * [x] Mesh update in viewport
    * [x] Motion blur (important: https://developer.blender.org/T60771)
    * [x] Autosmooth
  * [x] Light export
  * [x] World light export
  * [x] Material export
    * [x] Material viewport updates
    * [x] (Waiting for a fix of https://developer.blender.org/T66521) looks like we won't get one, we'll have to find a workaround (probably property update methods)
    * [x] Pointiness export
  * [x] Hair export
    * [x] Fix Export of Vertex Colors and UVs for hairs
* [x] Port viewport render draw code (there's a good example in the [Blender API docs](https://docs.blender.org/api/master/bpy.types.RenderEngine.html))
* [x] Viewport render
  * [x] Do session init in separate thread for responsive UI (maybe also mesh conversion)
  * [ ] Rework camera screenwindow calculation (can we use `context.region.view2d.view_to_region`?)
* [x] Final render
  * [x] Basics
  * [x] Tile Draw Handler
  * [x] Fix halt conditions not being updated during render (perhaps use `depsgraph.scene` instead of `depsgraph.scene_eval` in render engine for halt conditions)
* [x] Port the function that ensures that a material and it's custom node tree always have the same name

Extras:
* [x] LuxCore will have to change the Python version to the one 2.8 uses (3.7.0)
* [ ] Reopen issue #38 
* [ ] Choose new icons for better/worse/equal states in the statistics panel
* [x] Material preview
  * [x] Fix hair preview
  * [x] Check if we could replace blender shader ball with LuxCore shader ball
* [X] Use Cycles' "shadow_soft_size" property instead of our custom "radius" for point lights
* [ ] Cycles scene reader: #272
* [ ] Make it easier to find the denoised result, e.g. by replacing combined once a denoised result exists and writing the noisy raw output into an extra "NOISY" pass (the "DENOISED" pass would be removed)
* [ ] Fix motion blur for viewport renders
* [ ] Rewrite the main readme file, it is outdated

**Comment by Theverat** [comment]
Seems like there are some regressions in the RenderEngine API: https://devtalk.blender.org/t/2-8-render-engine-api-papercuts/6878

**Comment by Theverat** [comment]
New branch: https://github.com/LuxCoreRender/BlendLuxCore/tree/refactor/new_blender2.80

**Comment by Theverat** [comment]
Short status update:
**https://youtu.be/s_PkDk0zrkU**

**What works**
* Viewport render
* Node editor/materials
* @neo2068 has ported most of the UI panels
* Lights/World
* Objects (including particles and all other kinds of instances)

**Todo**
* Final render
* View layers
* Motion Blur
* Hair
* Material preview
* ... and a lot of polishing and probably tons of minor bugs that will pop up

Thanks to all the donors for their support! I appreciate it a lot.

**Comment by Theverat** [comment]
A first testbuild is available here: https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.2beta3
I also recorded a video about how to render a Cycles scene with LuxCore in this testbuild:
https://youtu.be/kglbpZl6Sck

**Comment by Theverat** [comment]
With the release of [BlendLuxCore v2.2](https://github.com/LuxCoreRender/BlendLuxCore/releases/tag/blendluxcore_v2.2) for both Blender 2.79 and 2.80 I consider this issue solved. 
I will share the bounty with @neo2068, who has contributed to this project.

Starting now, Blender 2.79 will no longer be supported by future versions of the addon and all development efforts will concentrate on Blender 2.80.
