### ISSUE TITLE
Support AOVs

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/BlendLuxCore#18]
See my question and answer here: https://blender.stackexchange.com/questions/100791/how-to-use-the-new-render-pass-api-for-an-external-renderer

### Todo
* [x] Implement basic AOVs that don't need an ID
* [x] Investigate what's going on with the CONVERGENCE Output (always -inf or something)
* [x] Investigate if we can make AOV import faster. Currently the times are like this:
```
Importing DEPTH took 0.368s
Importing UV took 0.647s
Importing ALPHA took 0.391s
```
* [x] Investigate what's going on with the IRRADIANCE output
* [x] light groups

BY_MATERIAL_ID etc. are not part of this issue, for those see #230
